{{- if .Values.dashboard.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.fullname" . }}-dashboard
  labels:
    grafana_dashboard: "1"
    {{- include "my-app.labels" . | nindent 4 }}
data:
  my-app-dashboard.json: |
    {
      "__inputs": [],
      "__requires": [],
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "links": [],
      "panels": [
        {
          "title": "Розподіл значень (Heatmap)",
          "type": "heatmap",
          "datasource": {
            "type": "prometheus",
            "uid": "VictoriaMetrics"
          },
          "gridPos": {
            "h": 10,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "targets": [
            {
              "refId": "A",
              "expr": "sum by (le) (\n  rate(ordered_histogram_bucket[5m])\n)",
              "legendFormat": "{{`{{le}}`}}",
              "datasource": {
                "type": "prometheus",
                "uid": "VictoriaMetrics"
              }
            }
          ],
          "cards": {
            "cardPadding": null,
            "cardRound": null
          },
          "color": {
            "mode": "palette-classic",
            "palette": "interpolateOranges",
            "scheme": "Oranges",
            "exponent": 0.5,
            "ska": 0,
            "skr": 0
          },
          "dataFormat": "time_series_buckets"
        }
      ],
      "refresh": "5s",
      "schemaVersion": 36,
      "style": "dark",
      "tags": [
        "prometheus",
        "histogram",
        "heatmap-only"
      ],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "browser",
      "title": "Histogram Heatmap (ordered_histogram)",
      "uid": "my-histogram-heatmap-12345",
      "version": 2
    }
{{- end }}
